### ISSUE TITLE
No support for multiprocess/electrolysis

### ISSUE THREAD

**Issue by Kasijjuf** [wodny/y-u-no-validate#5]
According to [Add-On Compatibility Reporter](https://addons.mozilla.org/en-US/firefox/addon/add-on-compatibility-reporter), Y U no validate doesn't support Firefox Multiprocess (also known as [Electrolysis](https://wiki.mozilla.org/Electrolysis)). Mozilla has several resources [here](https://developer.mozilla.org/en-US/Add-ons/Working_with_multiprocess_Firefox) to help with this processes.

**Comment by wodny** [comment]
I am afraid that deprecation of XUL is going to be an even grater problem in the near future. I am not sure if I will be able to modify the extension. Unfortunately Mozilla [does not want](https://bugzilla.mozilla.org/show_bug.cgi?id=762985) to add a setting for this. I will keep this issue open. Maybe I will have some time to check if I can do something about compatibility with new versions of Firefox.

**Comment by jrchamp** [comment]
Thank you for creating this extension to correctly default security settings to not trust invalid certificates. [Bug 1414753](https://bugzilla.mozilla.org/show_bug.cgi?id=1414753) seems to start the conversation again. The implementation of this plugin in the upstream code seems as simple as https://github.com/jrchamp/gecko-dev/commit/f13ad2775d4eb461fd5c1c416b9fad35c5aa104f

**Comment by jwilk** [comment]
Since Firefox 66, you can set `security.certerrors.permanentOverride` to false.

**Comment by wodny** [comment]
Thanks for pointing that out. For further reference:
- [bug report #1492498](https://bugzilla.mozilla.org/show_bug.cgi?id=1492498) with the patch and its discussion
- [changeset 6aefbed9ce430f1da6b59a4ff98fb69375fa4f8f](https://hg.mozilla.org/mozilla-central/rev/6aefbed9ce430f1da6b59a4ff98fb69375fa4f8f)
